spring.application.name=notification-service
server.port=8086

spring.cloud.config.enabled=true
spring.config.import=optional:configserver:${CONFIG_URL:http://localhost:9999}

spring.datasource.url=jdbc:h2:mem:notificationdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=
spring.datasource.password=

# Kafka Consumer
spring.kafka.consumer.group-id=notification-group
