spring.application.name=transaction-service
server.port=8083

# Config Server Import
spring.config.import=optional:configserver:${CONFIG_URL:http://localhost:9999}

spring.datasource.url=jdbc:h2:mem:transactiondb
spring.kafka.consumer.group-id=transaction-group
spring.kafka.topic.name=transaction-topic
