spring.application.name=user-service
server.port=8081

# Config Server Import
spring.config.import=optional:configserver:${CONFIG_URL:http://localhost:9999}

spring.datasource.url=jdbc:h2:mem:userdb
spring.kafka.topic.name=user-topic