spring.application.name=user-service
server.port=8081

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
#eureka.instance.prefer-ip-address=true


spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.topic.name=user-topic


spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8085/realms/banking-system-users-realm/protocol/openid-connect/certs
keycloak.realm=banking-system-users-realm

#keycloak.auth-server-url=${KEYCLOAK_URL:http://localhost:9090}
keycloak.auth-server-url=http://localhost:8085
keycloak.resource=banking-system-users-client
keycloak.credentials.secret=ODLpMAWh5xuFB3c4FTo96Dt6yhZHRqr4