spring.application.name=fraud-service
server.port=8084

# Config Server Import
spring.config.import=optional:configserver:${CONFIG_URL:http://localhost:9999}

spring.datasource.url=jdbc:h2:mem:frauddb

spring.kafka.consumer.group-id=fraud-group
spring.kafka.topic.name=fraud-topic
